language: node_js
node_js:
  - "10"
sudo: true

addons:
  chrome: stable

before_script:
  - npm install -g @angular/cli

script:
  - yarn all_tests
  - yarn build --prod --base-href $base_href #base_href should be given in travis as an environment variable
